@baseUrl = https://8080-marcossakaguchi-javaapi-fhbjlpo0tho.ws-us115.gitpod.io

###

GET {{baseUrl}}/alunos

###

POST {{baseUrl}}/alunos
Content-type: application/json

{
    "nome":"manbre 35"
}


###

GET {{baseUrl}}/alunos/1


###

PUT {{baseUrl}}/alunos/1
Content-type: application/json

{
    "nome":"bubu 35"
}

###

DELETE {{baseUrl}}/alunos/1